server:
  port: 10000

spring:
  application:
    name: mall-product
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.5.9.16:3306/mall_pms?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: nevergiveup?
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      # 主键自增
      id-type: auto
      # 逻辑删除，实体字段 @TableLogic
      logic-delete-value: 0 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 1 # 逻辑未删除值(默认为 0)

logging:
  level:
    com.llb.mall: debug
