server:
  port: 10000

spring:
  application:
    name: mall-product
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.5.9.16:3306/mall_pms?characterEncoding=utf-8
    username: root
    password: nevergiveup?
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  # 设置时间日期个格式
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  # 关闭缓存
  thymeleaf:
    cache: false

  # redis
  redis:
    host: 121.5.9.16
    port: 6379

  # cache
  cache:
    type: redis
    redis:
      time-to-live: 360000
      key-prefix: CACHE_ # key前缀，如果指定了前缀，就用我们指定的前缀，如果没有就默认使用缓存的名字作为前缀
      use-key-prefix: true  # 使用key前缀，默认true
      cache-null-values: true # 设置缓存为null，可以防止缓存穿透

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      # 主键自增
      id-type: auto
      # 逻辑删除，实体字段 @TableLogic
      logic-delete-value: 0 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 1 # 逻辑未删除值(默认为 0)

ribbon:
  # 指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ReadTimeout: 10000
  # 指的是建立连接后从服务器读取到可用资源所用时间
  ConnectTimeout: 10000


feign:
  hystrix:
    enabled: false

logging:
  level:
    com.llb.mall: debug
