server:
  port: 88

spring:
  application:
    name: mall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

#gateway
    gateway:
      routes:
#        - id: baidu_route
#          uri: http://www.baidu.com
#          predicates:
#            - Query=url,baidu
#
#        - id: qq_route
#          uri: http://www.qq.com
#          predicates:
#            - Query=url,qq

        - id: mall_product
          uri: lb://mall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: mall_third_party
          uri: lb://mall-third-party
          predicates:
            - Path=/api/thirdParty/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: mall_member
          uri: lb://mall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}
